import java.util.Random;

/**
 * Computes some statistics about families in which the parents decide
 * to have children until they have at least one child of each gender.
 * The program expects to get two command-line arguments: an int value
 * that determines how many families to simulate, and an int value
 * that serves as the seed of the random numbers generated by the program.
 * Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main(String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
		Random generator = new Random(seed);
		int numOfGirls = 0;
		int numOfBoys = 0;
		int numOfChildren = 0;
		int totalOfChildren = 0;
		int familiesTwoChildren = 0;
		int familiesThreeChildren = 0;
		int familiesWithMore = 0;

		for (int i = 0; i < T; i++) {

			while (numOfGirls < 1 || numOfBoys < 1) {

				double rnd = generator.nextDouble();
				if (rnd <= 0.5) {
					numOfGirls++;
				} else {
					numOfBoys++;
				}

				numOfChildren = numOfGirls + numOfBoys;
				totalOfChildren += numOfChildren;

				if (numOfChildren == 2) {
					familiesTwoChildren++;
				} else if (numOfChildren == 3) {
					familiesThreeChildren++;
				} else {
					familiesWithMore++;
				}
			}
		}

		double avarage = totalOfChildren / T;
		int max = (Math.max(Math.max(familiesTwoChildren, familiesThreeChildren), (familiesWithMore)));

		System.out.println("Average: " + avarage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + familiesTwoChildren);
		System.out.println("Number of families with 3 children: " + familiesThreeChildren);
		System.out.println("Number of families with 4 or more children: " + familiesWithMore);

		if (max == familiesTwoChildren) {
			System.out.println("The most common number of children is 2.");
		} else if (max == familiesThreeChildren) {
			System.out.println("The most common number of children is 3.");
		} else {
			System.out.println("The most common number of children is 4 or more.");
		}

	}

}
